
# --- CONEXÃO COM O BANCO DE DADOS (NEON / AWS) ---
# O Java exige o prefixo "jdbc:" antes do endereço
spring.datasource.url=jdbc:postgresql://ep-old-forest-ahv8u3ko-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require

# Credenciais do Neon
spring.datasource.username=neondb_owner
spring.datasource.password=npg_H5YG6sAoeBty

# O Driver oficial do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# --- COMPORTAMENTO DO JPA (Hibernate) ---
# "update": Se a tabela não existir, cria. Se mudar algo no Java, atualiza.
spring.jpa.hibernate.ddl-auto=update

# O Dialeto: Otimizações específicas para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# (Opcional) Mostra o SQL no terminal (útil para ver se está funcionando)
spring.jpa.show-sql=true

# --- CONFIGURAÇÃO DE UPLOAD DE ARQUIVOS ---
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB