spring.application.name=core-api

## 1. Configuração da Conexão (PostgreSQL)
# O endereço: localhost, porta 5432, banco portfolio_db
spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

## 2. Configuração do JPA / Hibernate
# Mostra o SQL que o Java está gerando no console (útil para aprender)
spring.jpa.show-sql=true
# Formata o SQL para ficar bonito de ler
spring.jpa.properties.hibernate.format_sql=true

## 3. DDL Auto (Atenção aqui!)
# "update": O Java verifica se a tabela existe. Se não existir, cria. Se mudou, atualiza.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect