# --- CONEXÃO COM O BANCO DE DADOS (VIA VARIÁVEIS DE AMBIENTE) ---

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# --- COMPORTAMENTO DO JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- UPLOAD ---
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB